--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) 
FROM customer_trend
GROUP BY gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id,discount_applied, purchase_amount
FROM customer_trend
WHERE discount_applied ='Yes' and purchase_amount >= (select AVG(purchase_amount) from customer_trend);

-- Q3. Which are the top 5 products with the highest average review rating?
select * from customer_trend

SELECT item_purchased, category, round(AVG(review_rating::numeric),2) as AVG_Rating
FROM customer_trend
GROUP By item_purchased,category
ORDER BY avg(review_rating) desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select*From customer_trend

SELECT shipping_type, round(avg(purchase_amount),2) as avg_purchase
FROM customer_trend
WHERE shipping_type = 'Express' or shipping_type = 'Standard'
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select * from customer_trend

SELECT subscription_status, count(customer_id) as total_customers,round(avg(purchase_amount),2) as avg_spend, sum(purchase_amount) as total_revenue
FROM customer_trend
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend desc;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer_trend
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
select * from customer_trend

with customer_type as (  -- new temp table name
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment -- new col created through temp table
FROM customer_trend)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type  
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_trend
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer_trend
WHERE previous_purchases > 5
GROUP BY subscription_status;
--Q10. What is the revenue contribution of each age group? 
select * from customer_trend

SELECT age_group, SUM(purchase_amount) as revenue_$
FROM customer_trend
GROUP BY age_group
ORDER BY revenue_$ desc 

